"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var ApiResponse = /** @class */ (function () {
    function ApiResponse() {
    }
    ApiResponse.getAttributeTypeMap = function () {
        return ApiResponse.attributeTypeMap;
    };
    ApiResponse.discriminator = undefined;
    ApiResponse.attributeTypeMap = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "{ [key: string]: Header; }"
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "BodyPartHeaders"
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "{ [key: string]: Link; }"
        },
        {
            "name": "extensions",
            "baseName": "extensions",
            "type": "{ [key: string]: any; }"
        },
        {
            "name": "get$ref",
            "baseName": "get$ref",
            "type": "string"
        }
    ];
    return ApiResponse;
}());
exports.ApiResponse = ApiResponse;
