"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BodyPartMediaType = /** @class */ (function () {
    function BodyPartMediaType() {
    }
    BodyPartMediaType.getAttributeTypeMap = function () {
        return BodyPartMediaType.attributeTypeMap;
    };
    BodyPartMediaType.discriminator = undefined;
    BodyPartMediaType.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "subtype",
            "baseName": "subtype",
            "type": "string"
        },
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "wildcardType",
            "baseName": "wildcardType",
            "type": "boolean"
        },
        {
            "name": "wildcardSubtype",
            "baseName": "wildcardSubtype",
            "type": "boolean"
        }
    ];
    return BodyPartMediaType;
}());
exports.BodyPartMediaType = BodyPartMediaType;
