"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTAppElementContentDeltaInfo = /** @class */ (function () {
    function BTAppElementContentDeltaInfo() {
    }
    BTAppElementContentDeltaInfo.getAttributeTypeMap = function () {
        return BTAppElementContentDeltaInfo.attributeTypeMap;
    };
    BTAppElementContentDeltaInfo.discriminator = undefined;
    BTAppElementContentDeltaInfo.attributeTypeMap = [
        {
            "name": "delta",
            "baseName": "delta",
            "type": "string"
        }
    ];
    return BTAppElementContentDeltaInfo;
}());
exports.BTAppElementContentDeltaInfo = BTAppElementContentDeltaInfo;
