"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTAppElementChangeParams = /** @class */ (function () {
    function BTAppElementChangeParams() {
    }
    BTAppElementChangeParams.getAttributeTypeMap = function () {
        return BTAppElementChangeParams.attributeTypeMap;
    };
    BTAppElementChangeParams.discriminator = undefined;
    BTAppElementChangeParams.attributeTypeMap = [
        {
            "name": "subelementId",
            "baseName": "subelementId",
            "type": "string"
        },
        {
            "name": "baseContent",
            "baseName": "baseContent",
            "type": "string"
        },
        {
            "name": "delta",
            "baseName": "delta",
            "type": "string"
        }
    ];
    return BTAppElementChangeParams;
}());
exports.BTAppElementChangeParams = BTAppElementChangeParams;
