"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTAppAssociativeDataParamsArray = /** @class */ (function () {
    function BTAppAssociativeDataParamsArray() {
    }
    BTAppAssociativeDataParamsArray.getAttributeTypeMap = function () {
        return BTAppAssociativeDataParamsArray.attributeTypeMap;
    };
    BTAppAssociativeDataParamsArray.discriminator = undefined;
    BTAppAssociativeDataParamsArray.attributeTypeMap = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BTAssociativeDataParams>"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string"
        },
        {
            "name": "parentChangeId",
            "baseName": "parentChangeId",
            "type": "string"
        }
    ];
    return BTAppAssociativeDataParamsArray;
}());
exports.BTAppAssociativeDataParamsArray = BTAppAssociativeDataParamsArray;
