"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTAutoPartNumberingSchemeParams = /** @class */ (function () {
    function BTAutoPartNumberingSchemeParams() {
    }
    BTAutoPartNumberingSchemeParams.getAttributeTypeMap = function () {
        return BTAutoPartNumberingSchemeParams.attributeTypeMap;
    };
    BTAutoPartNumberingSchemeParams.discriminator = undefined;
    BTAutoPartNumberingSchemeParams.attributeTypeMap = [
        {
            "name": "schemeId",
            "baseName": "schemeId",
            "type": "string"
        },
        {
            "name": "assemblyPrefix",
            "baseName": "assemblyPrefix",
            "type": "string"
        },
        {
            "name": "drawingPrefix",
            "baseName": "drawingPrefix",
            "type": "string"
        },
        {
            "name": "filePrefix",
            "baseName": "filePrefix",
            "type": "string"
        },
        {
            "name": "partPrefix",
            "baseName": "partPrefix",
            "type": "string"
        },
        {
            "name": "nextNumber",
            "baseName": "nextNumber",
            "type": "number"
        },
        {
            "name": "nextNumberMinWidth",
            "baseName": "nextNumberMinWidth",
            "type": "number"
        }
    ];
    return BTAutoPartNumberingSchemeParams;
}());
exports.BTAutoPartNumberingSchemeParams = BTAutoPartNumberingSchemeParams;
