"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTBetaCapabilityMetricsInfo = /** @class */ (function () {
    function BTBetaCapabilityMetricsInfo() {
    }
    BTBetaCapabilityMetricsInfo.getAttributeTypeMap = function () {
        return BTBetaCapabilityMetricsInfo.attributeTypeMap;
    };
    BTBetaCapabilityMetricsInfo.discriminator = undefined;
    BTBetaCapabilityMetricsInfo.attributeTypeMap = [
        {
            "name": "statePreApproved",
            "baseName": "statePreApproved",
            "type": "number"
        },
        {
            "name": "stateRequested",
            "baseName": "stateRequested",
            "type": "number"
        },
        {
            "name": "stateApproved",
            "baseName": "stateApproved",
            "type": "number"
        },
        {
            "name": "stateRemoved",
            "baseName": "stateRemoved",
            "type": "number"
        },
        {
            "name": "approvedPreApproved",
            "baseName": "approvedPreApproved",
            "type": "number"
        },
        {
            "name": "approvedRequested",
            "baseName": "approvedRequested",
            "type": "number"
        },
        {
            "name": "approvedPaid",
            "baseName": "approvedPaid",
            "type": "number"
        },
        {
            "name": "approvedOnshape",
            "baseName": "approvedOnshape",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTBetaCapabilityMetricsInfo;
}());
exports.BTBetaCapabilityMetricsInfo = BTBetaCapabilityMetricsInfo;
