"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTCapableInfo = /** @class */ (function () {
    function BTCapableInfo() {
    }
    BTCapableInfo.getAttributeTypeMap = function () {
        return BTCapableInfo.attributeTypeMap;
    };
    BTCapableInfo.discriminator = undefined;
    BTCapableInfo.attributeTypeMap = [
        {
            "name": "capable",
            "baseName": "capable",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTCapableInfo;
}());
exports.BTCapableInfo = BTCapableInfo;
