"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTCardInfo = /** @class */ (function () {
    function BTCardInfo() {
    }
    BTCardInfo.getAttributeTypeMap = function () {
        return BTCardInfo.attributeTypeMap;
    };
    BTCardInfo.discriminator = undefined;
    BTCardInfo.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "billingAddress",
            "baseName": "billingAddress",
            "type": "BTAddressInfo"
        },
        {
            "name": "last4",
            "baseName": "last4",
            "type": "string"
        },
        {
            "name": "expMonth",
            "baseName": "expMonth",
            "type": "number"
        },
        {
            "name": "expYear",
            "baseName": "expYear",
            "type": "number"
        }
    ];
    return BTCardInfo;
}());
exports.BTCardInfo = BTCardInfo;
