"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTCapabilityRuleParams = /** @class */ (function () {
    function BTCapabilityRuleParams() {
    }
    BTCapabilityRuleParams.getAttributeTypeMap = function () {
        return BTCapabilityRuleParams.attributeTypeMap;
    };
    BTCapabilityRuleParams.discriminator = undefined;
    BTCapabilityRuleParams.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "script",
            "baseName": "script",
            "type": "string"
        }
    ];
    return BTCapabilityRuleParams;
}());
exports.BTCapabilityRuleParams = BTCapabilityRuleParams;
