"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTChangeContextParams = /** @class */ (function () {
    function BTChangeContextParams() {
    }
    BTChangeContextParams.getAttributeTypeMap = function () {
        return BTChangeContextParams.attributeTypeMap;
    };
    BTChangeContextParams.discriminator = undefined;
    BTChangeContextParams.attributeTypeMap = [
        {
            "name": "contextPath",
            "baseName": "contextPath",
            "type": "Array<string>"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "contextId",
            "baseName": "contextId",
            "type": "string"
        }
    ];
    return BTChangeContextParams;
}());
exports.BTChangeContextParams = BTChangeContextParams;
