"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTCompanyPoliciesParams = /** @class */ (function () {
    function BTCompanyPoliciesParams() {
    }
    BTCompanyPoliciesParams.getAttributeTypeMap = function () {
        return BTCompanyPoliciesParams.attributeTypeMap;
    };
    BTCompanyPoliciesParams.discriminator = undefined;
    BTCompanyPoliciesParams.attributeTypeMap = [
        {
            "name": "requireTotp",
            "baseName": "requireTotp",
            "type": "boolean"
        },
        {
            "name": "useLightUi",
            "baseName": "useLightUi",
            "type": "boolean"
        },
        {
            "name": "onlyAdminsCanMarkObjectsAsNotRevisionManaged",
            "baseName": "onlyAdminsCanMarkObjectsAsNotRevisionManaged",
            "type": "boolean"
        },
        {
            "name": "requireApprovedDrawingTemplates",
            "baseName": "requireApprovedDrawingTemplates",
            "type": "boolean"
        },
        {
            "name": "approvedDrawingTemplatesDocumentId",
            "baseName": "approvedDrawingTemplatesDocumentId",
            "type": "string"
        },
        {
            "name": "addCompanyOwnedLibrariesInUserAccount",
            "baseName": "addCompanyOwnedLibrariesInUserAccount",
            "type": "boolean"
        },
        {
            "name": "releaseWorkflowId",
            "baseName": "releaseWorkflowId",
            "type": "string"
        },
        {
            "name": "obsoletionWorkflowId",
            "baseName": "obsoletionWorkflowId",
            "type": "string"
        },
        {
            "name": "revisionSchemeId",
            "baseName": "revisionSchemeId",
            "type": "string"
        },
        {
            "name": "requireRevisionForReleasedObjects",
            "baseName": "requireRevisionForReleasedObjects",
            "type": "boolean"
        },
        {
            "name": "requirePartNumberForReleasedObjects",
            "baseName": "requirePartNumberForReleasedObjects",
            "type": "boolean"
        },
        {
            "name": "onlyAdminsCanEditPropertiesOfReleasedObjects",
            "baseName": "onlyAdminsCanEditPropertiesOfReleasedObjects",
            "type": "boolean"
        },
        {
            "name": "onlyAdminsCanDeleteDocumentsContainingReleasedObjects",
            "baseName": "onlyAdminsCanDeleteDocumentsContainingReleasedObjects",
            "type": "boolean"
        },
        {
            "name": "onlyAdminsCanApproveReleases",
            "baseName": "onlyAdminsCanApproveReleases",
            "type": "boolean"
        },
        {
            "name": "requirePartsAndSubassembliesReleaseWithAssembly",
            "baseName": "requirePartsAndSubassembliesReleaseWithAssembly",
            "type": "boolean"
        },
        {
            "name": "requirePartsAndSubassembliesReleaseWithDrawing",
            "baseName": "requirePartsAndSubassembliesReleaseWithDrawing",
            "type": "boolean"
        },
        {
            "name": "requireBasePartReleaseWithDerivedPart",
            "baseName": "requireBasePartReleaseWithDerivedPart",
            "type": "boolean"
        },
        {
            "name": "requireImageReleaseWithDrawing",
            "baseName": "requireImageReleaseWithDrawing",
            "type": "boolean"
        },
        {
            "name": "actionShowDrawingsWatermark",
            "baseName": "actionShowDrawingsWatermark",
            "type": "boolean"
        },
        {
            "name": "preventDuplicateDocumentNameRegex",
            "baseName": "preventDuplicateDocumentNameRegex",
            "type": "string"
        },
        {
            "name": "errorOnFeatureListErrorsDuringRelease",
            "baseName": "errorOnFeatureListErrorsDuringRelease",
            "type": "boolean"
        },
        {
            "name": "errorOnRollbackBarNotAtEndDuringRelease",
            "baseName": "errorOnRollbackBarNotAtEndDuringRelease",
            "type": "boolean"
        },
        {
            "name": "errorOnAssemblyTreeErrorsDuringRelease",
            "baseName": "errorOnAssemblyTreeErrorsDuringRelease",
            "type": "boolean"
        },
        {
            "name": "errorOnPendingContextEditsDuringRelease",
            "baseName": "errorOnPendingContextEditsDuringRelease",
            "type": "boolean"
        },
        {
            "name": "errorOnPendingDrawingUpdateDuringRelease",
            "baseName": "errorOnPendingDrawingUpdateDuringRelease",
            "type": "boolean"
        },
        {
            "name": "errorOnPendingDanglingDrawingObjectsDuringRelease",
            "baseName": "errorOnPendingDanglingDrawingObjectsDuringRelease",
            "type": "boolean"
        },
        {
            "name": "approverRequiredDuringRelease",
            "baseName": "approverRequiredDuringRelease",
            "type": "boolean"
        },
        {
            "name": "noteRequiredDuringRelease",
            "baseName": "noteRequiredDuringRelease",
            "type": "boolean"
        },
        {
            "name": "requireAllApprovers",
            "baseName": "requireAllApprovers",
            "type": "boolean"
        },
        {
            "name": "automaticallyObsoletePreviousReleasedRevisions",
            "baseName": "automaticallyObsoletePreviousReleasedRevisions",
            "type": "boolean"
        },
        {
            "name": "partNumberingSchemeId",
            "baseName": "partNumberingSchemeId",
            "type": "string"
        },
        {
            "name": "requirePeerReview",
            "baseName": "requirePeerReview",
            "type": "boolean"
        },
        {
            "name": "drawingCanDuplicatePartNumber",
            "baseName": "drawingCanDuplicatePartNumber",
            "type": "boolean"
        }
    ];
    return BTCompanyPoliciesParams;
}());
exports.BTCompanyPoliciesParams = BTCompanyPoliciesParams;
