/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTColorInfo {
    'blue'?: number;
    'red'?: number;
    'green'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "blue",
            "baseName": "blue",
            "type": "number"
        },
        {
            "name": "red",
            "baseName": "red",
            "type": "number"
        },
        {
            "name": "green",
            "baseName": "green",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BTColorInfo.attributeTypeMap;
    }
}

