"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTCopyElementParams = /** @class */ (function () {
    function BTCopyElementParams() {
    }
    BTCopyElementParams.getAttributeTypeMap = function () {
        return BTCopyElementParams.attributeTypeMap;
    };
    BTCopyElementParams.discriminator = undefined;
    BTCopyElementParams.attributeTypeMap = [
        {
            "name": "documentIdSource",
            "baseName": "documentIdSource",
            "type": "string"
        },
        {
            "name": "workspaceIdSource",
            "baseName": "workspaceIdSource",
            "type": "string"
        },
        {
            "name": "elementIdSource",
            "baseName": "elementIdSource",
            "type": "string"
        },
        {
            "name": "anchorElementId",
            "baseName": "anchorElementId",
            "type": "string"
        },
        {
            "name": "isGroupAnchor",
            "baseName": "isGroupAnchor",
            "type": "boolean"
        }
    ];
    return BTCopyElementParams;
}());
exports.BTCopyElementParams = BTCopyElementParams;
