"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTConfigurationParams = /** @class */ (function () {
    function BTConfigurationParams() {
    }
    BTConfigurationParams.getAttributeTypeMap = function () {
        return BTConfigurationParams.attributeTypeMap;
    };
    BTConfigurationParams.discriminator = undefined;
    BTConfigurationParams.attributeTypeMap = [
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<ConfigurationEntry>"
        },
        {
            "name": "standardContentParametersId",
            "baseName": "standardContentParametersId",
            "type": "string"
        }
    ];
    return BTConfigurationParams;
}());
exports.BTConfigurationParams = BTConfigurationParams;
