"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTDocumentElementInfo = /** @class */ (function () {
    function BTDocumentElementInfo() {
    }
    BTDocumentElementInfo.getAttributeTypeMap = function () {
        return BTDocumentElementInfo.attributeTypeMap;
    };
    BTDocumentElementInfo.discriminator = undefined;
    BTDocumentElementInfo.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "elementType",
            "baseName": "elementType",
            "type": "BTDocumentElementInfo.ElementTypeEnum"
        },
        {
            "name": "dataType",
            "baseName": "dataType",
            "type": "string"
        },
        {
            "name": "thumbnails",
            "baseName": "thumbnails",
            "type": "string"
        },
        {
            "name": "microversionId",
            "baseName": "microversionId",
            "type": "string"
        },
        {
            "name": "filename",
            "baseName": "filename",
            "type": "string"
        },
        {
            "name": "thumbnailInfo",
            "baseName": "thumbnailInfo",
            "type": "BTThumbnailInfo"
        },
        {
            "name": "foreignDataId",
            "baseName": "foreignDataId",
            "type": "string"
        },
        {
            "name": "lengthUnits",
            "baseName": "lengthUnits",
            "type": "string"
        },
        {
            "name": "angleUnits",
            "baseName": "angleUnits",
            "type": "string"
        },
        {
            "name": "massUnits",
            "baseName": "massUnits",
            "type": "string"
        }
    ];
    return BTDocumentElementInfo;
}());
exports.BTDocumentElementInfo = BTDocumentElementInfo;
(function (BTDocumentElementInfo) {
    var ElementTypeEnum;
    (function (ElementTypeEnum) {
        ElementTypeEnum[ElementTypeEnum["PARTSTUDIO"] = 'PARTSTUDIO'] = "PARTSTUDIO";
        ElementTypeEnum[ElementTypeEnum["ASSEMBLY"] = 'ASSEMBLY'] = "ASSEMBLY";
        ElementTypeEnum[ElementTypeEnum["DRAWING"] = 'DRAWING'] = "DRAWING";
        ElementTypeEnum[ElementTypeEnum["FEATURESTUDIO"] = 'FEATURESTUDIO'] = "FEATURESTUDIO";
        ElementTypeEnum[ElementTypeEnum["BLOB"] = 'BLOB'] = "BLOB";
        ElementTypeEnum[ElementTypeEnum["APPLICATION"] = 'APPLICATION'] = "APPLICATION";
        ElementTypeEnum[ElementTypeEnum["TABLE"] = 'TABLE'] = "TABLE";
        ElementTypeEnum[ElementTypeEnum["BILLOFMATERIALS"] = 'BILLOFMATERIALS'] = "BILLOFMATERIALS";
        ElementTypeEnum[ElementTypeEnum["UNKNOWN"] = 'UNKNOWN'] = "UNKNOWN";
    })(ElementTypeEnum = BTDocumentElementInfo.ElementTypeEnum || (BTDocumentElementInfo.ElementTypeEnum = {}));
})(BTDocumentElementInfo = exports.BTDocumentElementInfo || (exports.BTDocumentElementInfo = {}));
exports.BTDocumentElementInfo = BTDocumentElementInfo;
