"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTExportModelBody = /** @class */ (function () {
    function BTExportModelBody() {
    }
    BTExportModelBody.getAttributeTypeMap = function () {
        return BTExportModelBody.attributeTypeMap;
    };
    BTExportModelBody.discriminator = undefined;
    BTExportModelBody.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "BTExportModelBody.TypeEnum"
        },
        {
            "name": "edges",
            "baseName": "edges",
            "type": "Array<BTExportModelEdge>"
        },
        {
            "name": "faces",
            "baseName": "faces",
            "type": "Array<BTExportModelFace>"
        },
        {
            "name": "vertices",
            "baseName": "vertices",
            "type": "Array<BTExportModelVertex>"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTExportModelBody;
}());
exports.BTExportModelBody = BTExportModelBody;
(function (BTExportModelBody) {
    var TypeEnum;
    (function (TypeEnum) {
        TypeEnum[TypeEnum["SOLID"] = 'SOLID'] = "SOLID";
        TypeEnum[TypeEnum["SURFACE"] = 'SURFACE'] = "SURFACE";
        TypeEnum[TypeEnum["UNKNOWN"] = 'UNKNOWN'] = "UNKNOWN";
    })(TypeEnum = BTExportModelBody.TypeEnum || (BTExportModelBody.TypeEnum = {}));
})(BTExportModelBody = exports.BTExportModelBody || (exports.BTExportModelBody = {}));
exports.BTExportModelBody = BTExportModelBody;
