"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTExportModelParams = /** @class */ (function () {
    function BTExportModelParams() {
    }
    BTExportModelParams.getAttributeTypeMap = function () {
        return BTExportModelParams.attributeTypeMap;
    };
    BTExportModelParams.discriminator = undefined;
    BTExportModelParams.attributeTypeMap = [
        {
            "name": "microversion",
            "baseName": "microversion",
            "type": "string"
        },
        {
            "name": "linkDocumentId",
            "baseName": "linkDocumentId",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "documentVersionId",
            "baseName": "documentVersionId",
            "type": "string"
        },
        {
            "name": "linkDocumentWorkspaceId",
            "baseName": "linkDocumentWorkspaceId",
            "type": "string"
        },
        {
            "name": "sheetMetalFlat",
            "baseName": "sheetMetalFlat",
            "type": "boolean"
        },
        {
            "name": "includeBendLines",
            "baseName": "includeBendLines",
            "type": "boolean"
        },
        {
            "name": "includeSketches",
            "baseName": "includeSketches",
            "type": "boolean"
        },
        {
            "name": "flatten",
            "baseName": "flatten",
            "type": "boolean"
        },
        {
            "name": "splinesAsPolylines",
            "baseName": "splinesAsPolylines",
            "type": "boolean"
        },
        {
            "name": "isPartingOut",
            "baseName": "isPartingOut",
            "type": "boolean"
        },
        {
            "name": "includeBendCenterlines",
            "baseName": "includeBendCenterlines",
            "type": "boolean"
        },
        {
            "name": "batchFlatPatterns",
            "baseName": "batchFlatPatterns",
            "type": "boolean"
        },
        {
            "name": "scale",
            "baseName": "scale",
            "type": "number"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string"
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "string"
        },
        {
            "name": "format",
            "baseName": "format",
            "type": "string"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "string"
        },
        {
            "name": "view",
            "baseName": "view",
            "type": "string"
        },
        {
            "name": "cloudObjectId",
            "baseName": "cloudObjectId",
            "type": "string"
        },
        {
            "name": "angleTolerance",
            "baseName": "angleTolerance",
            "type": "number"
        },
        {
            "name": "chordTolerance",
            "baseName": "chordTolerance",
            "type": "number"
        },
        {
            "name": "partIds",
            "baseName": "partIds",
            "type": "string"
        },
        {
            "name": "partQuery",
            "baseName": "partQuery",
            "type": "string"
        },
        {
            "name": "maxFacetWidth",
            "baseName": "maxFacetWidth",
            "type": "number"
        },
        {
            "name": "triggerAutoDownload",
            "baseName": "triggerAutoDownload",
            "type": "boolean"
        },
        {
            "name": "fromUserId",
            "baseName": "fromUserId",
            "type": "string"
        },
        {
            "name": "cloudStorageAccountId",
            "baseName": "cloudStorageAccountId",
            "type": "string"
        },
        {
            "name": "emailAttachment",
            "baseName": "emailAttachment",
            "type": "boolean"
        },
        {
            "name": "emailLink",
            "baseName": "emailLink",
            "type": "boolean"
        },
        {
            "name": "emailSubject",
            "baseName": "emailSubject",
            "type": "string"
        },
        {
            "name": "emailMessage",
            "baseName": "emailMessage",
            "type": "string"
        },
        {
            "name": "emailTo",
            "baseName": "emailTo",
            "type": "Array<string>"
        },
        {
            "name": "sendCopyToMe",
            "baseName": "sendCopyToMe",
            "type": "boolean"
        },
        {
            "name": "destinationName",
            "baseName": "destinationName",
            "type": "string"
        },
        {
            "name": "storeInDocument",
            "baseName": "storeInDocument",
            "type": "boolean"
        },
        {
            "name": "elementIds",
            "baseName": "elementIds",
            "type": "string"
        },
        {
            "name": "includeExportIds",
            "baseName": "includeExportIds",
            "type": "boolean"
        },
        {
            "name": "featureIds",
            "baseName": "featureIds",
            "type": "string"
        },
        {
            "name": "minFacetWidth",
            "baseName": "minFacetWidth",
            "type": "number"
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "string"
        },
        {
            "name": "grouping",
            "baseName": "grouping",
            "type": "string"
        },
        {
            "name": "zipSingleFileOutput",
            "baseName": "zipSingleFileOutput",
            "type": "boolean"
        },
        {
            "name": "includeForeignData",
            "baseName": "includeForeignData",
            "type": "boolean"
        },
        {
            "name": "deepSearchForForeignData",
            "baseName": "deepSearchForForeignData",
            "type": "boolean"
        },
        {
            "name": "includeStd",
            "baseName": "includeStd",
            "type": "boolean"
        },
        {
            "name": "includeReleaseManagementData",
            "baseName": "includeReleaseManagementData",
            "type": "boolean"
        },
        {
            "name": "includeLinkedDocuments",
            "baseName": "includeLinkedDocuments",
            "type": "boolean"
        },
        {
            "name": "extractToS3",
            "baseName": "extractToS3",
            "type": "boolean"
        }
    ];
    return BTExportModelParams;
}());
exports.BTExportModelParams = BTExportModelParams;
