"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTExternalElementReferenceInfo = /** @class */ (function () {
    function BTExternalElementReferenceInfo() {
    }
    BTExternalElementReferenceInfo.getAttributeTypeMap = function () {
        return BTExternalElementReferenceInfo.attributeTypeMap;
    };
    BTExternalElementReferenceInfo.discriminator = undefined;
    BTExternalElementReferenceInfo.attributeTypeMap = [
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "elementMicroversionId",
            "baseName": "elementMicroversionId",
            "type": "string"
        }
    ];
    return BTExternalElementReferenceInfo;
}());
exports.BTExternalElementReferenceInfo = BTExternalElementReferenceInfo;
