"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTFeatureScriptEvalCall = /** @class */ (function () {
    function BTFeatureScriptEvalCall() {
    }
    BTFeatureScriptEvalCall.getAttributeTypeMap = function () {
        return BTFeatureScriptEvalCall.attributeTypeMap;
    };
    BTFeatureScriptEvalCall.discriminator = undefined;
    BTFeatureScriptEvalCall.attributeTypeMap = [
        {
            "name": "script",
            "baseName": "script",
            "type": "string"
        },
        {
            "name": "queries",
            "baseName": "queries",
            "type": "{ [key: string]: Array<string>; }"
        },
        {
            "name": "belScriptLibraryVersion",
            "baseName": "belScriptLibraryVersion",
            "type": "BTBelScriptLibraryVersion"
        },
        {
            "name": "sourceMicroversion",
            "baseName": "sourceMicroversion",
            "type": "string"
        },
        {
            "name": "rejectMicroversionSkew",
            "baseName": "rejectMicroversionSkew",
            "type": "boolean"
        },
        {
            "name": "serializationVersion",
            "baseName": "serializationVersion",
            "type": "string"
        },
        {
            "name": "libraryVersion",
            "baseName": "libraryVersion",
            "type": "number"
        },
        {
            "name": "microversionSkew",
            "baseName": "microversionSkew",
            "type": "boolean"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTFeatureScriptEvalCall;
}());
exports.BTFeatureScriptEvalCall = BTFeatureScriptEvalCall;
