"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTIdTranslationParams = /** @class */ (function () {
    function BTIdTranslationParams() {
    }
    BTIdTranslationParams.getAttributeTypeMap = function () {
        return BTIdTranslationParams.attributeTypeMap;
    };
    BTIdTranslationParams.discriminator = undefined;
    BTIdTranslationParams.attributeTypeMap = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>"
        },
        {
            "name": "linkDocumentId",
            "baseName": "linkDocumentId",
            "type": "string"
        },
        {
            "name": "sourceDocumentMicroversion",
            "baseName": "sourceDocumentMicroversion",
            "type": "string"
        },
        {
            "name": "sourceConfiguration",
            "baseName": "sourceConfiguration",
            "type": "string"
        },
        {
            "name": "targetConfiguration",
            "baseName": "targetConfiguration",
            "type": "string"
        }
    ];
    return BTIdTranslationParams;
}());
exports.BTIdTranslationParams = BTIdTranslationParams;
