"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTMetadataPropertyValidatorInfo = /** @class */ (function () {
    function BTMetadataPropertyValidatorInfo() {
    }
    BTMetadataPropertyValidatorInfo.getAttributeTypeMap = function () {
        return BTMetadataPropertyValidatorInfo.attributeTypeMap;
    };
    BTMetadataPropertyValidatorInfo.discriminator = undefined;
    BTMetadataPropertyValidatorInfo.attributeTypeMap = [
        {
            "name": "max",
            "baseName": "max",
            "type": "number"
        },
        {
            "name": "min",
            "baseName": "min",
            "type": "number"
        },
        {
            "name": "pattern",
            "baseName": "pattern",
            "type": "string"
        },
        {
            "name": "minLength",
            "baseName": "minLength",
            "type": "number"
        },
        {
            "name": "maxLength",
            "baseName": "maxLength",
            "type": "number"
        },
        {
            "name": "minDate",
            "baseName": "minDate",
            "type": "Date"
        },
        {
            "name": "maxDate",
            "baseName": "maxDate",
            "type": "Date"
        },
        {
            "name": "minCount",
            "baseName": "minCount",
            "type": "number"
        },
        {
            "name": "maxCount",
            "baseName": "maxCount",
            "type": "number"
        }
    ];
    return BTMetadataPropertyValidatorInfo;
}());
exports.BTMetadataPropertyValidatorInfo = BTMetadataPropertyValidatorInfo;
