"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTMetadataPropertyUiHintsInfo = /** @class */ (function () {
    function BTMetadataPropertyUiHintsInfo() {
    }
    BTMetadataPropertyUiHintsInfo.getAttributeTypeMap = function () {
        return BTMetadataPropertyUiHintsInfo.attributeTypeMap;
    };
    BTMetadataPropertyUiHintsInfo.discriminator = undefined;
    BTMetadataPropertyUiHintsInfo.attributeTypeMap = [
        {
            "name": "multiline",
            "baseName": "multiline",
            "type": "boolean"
        }
    ];
    return BTMetadataPropertyUiHintsInfo;
}());
exports.BTMetadataPropertyUiHintsInfo = BTMetadataPropertyUiHintsInfo;
