"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTMobileNotificationParams = /** @class */ (function () {
    function BTMobileNotificationParams() {
    }
    BTMobileNotificationParams.getAttributeTypeMap = function () {
        return BTMobileNotificationParams.attributeTypeMap;
    };
    BTMobileNotificationParams.discriminator = undefined;
    BTMobileNotificationParams.attributeTypeMap = [
        {
            "name": "itemsToAcknowledge",
            "baseName": "itemsToAcknowledge",
            "type": "Array<Item>"
        }
    ];
    return BTMobileNotificationParams;
}());
exports.BTMobileNotificationParams = BTMobileNotificationParams;
