"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTNotificationDebugParams = /** @class */ (function () {
    function BTNotificationDebugParams() {
    }
    BTNotificationDebugParams.getAttributeTypeMap = function () {
        return BTNotificationDebugParams.attributeTypeMap;
    };
    BTNotificationDebugParams.discriminator = undefined;
    BTNotificationDebugParams.attributeTypeMap = [
        {
            "name": "debugSubmitted",
            "baseName": "debugSubmitted",
            "type": "boolean"
        }
    ];
    return BTNotificationDebugParams;
}());
exports.BTNotificationDebugParams = BTNotificationDebugParams;
