"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTPartIdParams = /** @class */ (function () {
    function BTPartIdParams() {
    }
    BTPartIdParams.getAttributeTypeMap = function () {
        return BTPartIdParams.attributeTypeMap;
    };
    BTPartIdParams.discriminator = undefined;
    BTPartIdParams.attributeTypeMap = [
        {
            "name": "ids",
            "baseName": "ids",
            "type": "Array<string>"
        },
        {
            "name": "linkDocumentId",
            "baseName": "linkDocumentId",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "string"
        }
    ];
    return BTPartIdParams;
}());
exports.BTPartIdParams = BTPartIdParams;
