"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTPartMaterialInfo = /** @class */ (function () {
    function BTPartMaterialInfo() {
    }
    BTPartMaterialInfo.getAttributeTypeMap = function () {
        return BTPartMaterialInfo.attributeTypeMap;
    };
    BTPartMaterialInfo.discriminator = undefined;
    BTPartMaterialInfo.attributeTypeMap = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<BTPartMaterialPropertyInfo>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string"
        },
        {
            "name": "libraryReference",
            "baseName": "libraryReference",
            "type": "BTExternalElementReferenceInfo"
        },
        {
            "name": "libraryName",
            "baseName": "libraryName",
            "type": "string"
        }
    ];
    return BTPartMaterialInfo;
}());
exports.BTPartMaterialInfo = BTPartMaterialInfo;
