"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTPartAppearanceInfo = /** @class */ (function () {
    function BTPartAppearanceInfo() {
    }
    BTPartAppearanceInfo.getAttributeTypeMap = function () {
        return BTPartAppearanceInfo.attributeTypeMap;
    };
    BTPartAppearanceInfo.discriminator = undefined;
    BTPartAppearanceInfo.attributeTypeMap = [
        {
            "name": "color",
            "baseName": "color",
            "type": "BTColorInfo"
        },
        {
            "name": "opacity",
            "baseName": "opacity",
            "type": "number"
        },
        {
            "name": "isGenerated",
            "baseName": "isGenerated",
            "type": "boolean"
        }
    ];
    return BTPartAppearanceInfo;
}());
exports.BTPartAppearanceInfo = BTPartAppearanceInfo;
