"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTPLiteralString = /** @class */ (function () {
    function BTPLiteralString() {
    }
    BTPLiteralString.getAttributeTypeMap = function () {
        return BTPLiteralString.attributeTypeMap;
    };
    BTPLiteralString.discriminator = undefined;
    BTPLiteralString.attributeTypeMap = [
        {
            "name": "value",
            "baseName": "value",
            "type": "string"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "shortDescriptor",
            "baseName": "shortDescriptor",
            "type": "string"
        },
        {
            "name": "firstChildField",
            "baseName": "firstChildField",
            "type": "number"
        },
        {
            "name": "changeableChildFieldIndices",
            "baseName": "changeableChildFieldIndices",
            "type": "Array<number>"
        },
        {
            "name": "startSourceLocation",
            "baseName": "startSourceLocation",
            "type": "number"
        },
        {
            "name": "endSourceLocation",
            "baseName": "endSourceLocation",
            "type": "number"
        },
        {
            "name": "atomic",
            "baseName": "atomic",
            "type": "boolean"
        },
        {
            "name": "documentationType",
            "baseName": "documentationType",
            "type": "BTPLiteralString.DocumentationTypeEnum"
        },
        {
            "name": "spaceBefore",
            "baseName": "spaceBefore",
            "type": "BTPSpace"
        },
        {
            "name": "spaceDefault",
            "baseName": "spaceDefault",
            "type": "boolean"
        },
        {
            "name": "spaceAfter",
            "baseName": "spaceAfter",
            "type": "BTPSpace"
        },
        {
            "name": "nodeId",
            "baseName": "nodeId",
            "type": "string"
        },
        {
            "name": "childMapIndices",
            "baseName": "childMapIndices",
            "type": "Array<number>"
        },
        {
            "name": "atomicChildIndices",
            "baseName": "atomicChildIndices",
            "type": "Array<number>"
        },
        {
            "name": "nodeIdRaw",
            "baseName": "nodeIdRaw",
            "type": "BTObjectId"
        },
        {
            "name": "childListIndices",
            "baseName": "childListIndices",
            "type": "Array<number>"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTPLiteralString;
}());
exports.BTPLiteralString = BTPLiteralString;
(function (BTPLiteralString) {
    var DocumentationTypeEnum;
    (function (DocumentationTypeEnum) {
        DocumentationTypeEnum[DocumentationTypeEnum["FUNCTION"] = 'FUNCTION'] = "FUNCTION";
        DocumentationTypeEnum[DocumentationTypeEnum["PREDICATE"] = 'PREDICATE'] = "PREDICATE";
        DocumentationTypeEnum[DocumentationTypeEnum["CONSTANT"] = 'CONSTANT'] = "CONSTANT";
        DocumentationTypeEnum[DocumentationTypeEnum["ENUM"] = 'ENUM'] = "ENUM";
        DocumentationTypeEnum[DocumentationTypeEnum["USERTYPE"] = 'USER_TYPE'] = "USERTYPE";
        DocumentationTypeEnum[DocumentationTypeEnum["FEATUREDEFINITION"] = 'FEATURE_DEFINITION'] = "FEATUREDEFINITION";
        DocumentationTypeEnum[DocumentationTypeEnum["FILEHEADER"] = 'FILE_HEADER'] = "FILEHEADER";
        DocumentationTypeEnum[DocumentationTypeEnum["UNDOCUMENTABLE"] = 'UNDOCUMENTABLE'] = "UNDOCUMENTABLE";
        DocumentationTypeEnum[DocumentationTypeEnum["UNKNOWN"] = 'UNKNOWN'] = "UNKNOWN";
    })(DocumentationTypeEnum = BTPLiteralString.DocumentationTypeEnum || (BTPLiteralString.DocumentationTypeEnum = {}));
})(BTPLiteralString = exports.BTPLiteralString || (exports.BTPLiteralString = {}));
exports.BTPLiteralString = BTPLiteralString;
