/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTPublishWorkflowParams {
    'name'?: string;
    'description'?: string;
    'workspaceId'?: string;
    'elementId'?: string;
    'documentId'?: string;
    'workflowType'?: BTPublishWorkflowParams.WorkflowTypeEnum;
    'isObsoletion'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        },
        {
            "name": "workflowType",
            "baseName": "workflowType",
            "type": "BTPublishWorkflowParams.WorkflowTypeEnum"
        },
        {
            "name": "isObsoletion",
            "baseName": "isObsoletion",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BTPublishWorkflowParams.attributeTypeMap;
    }
}

export namespace BTPublishWorkflowParams {
    export enum WorkflowTypeEnum {
        TEST = <any> 'TEST',
        RELEASE = <any> 'RELEASE'
    }
}
