"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTRevisionCustomData = /** @class */ (function () {
    function BTRevisionCustomData() {
    }
    BTRevisionCustomData.getAttributeTypeMap = function () {
        return BTRevisionCustomData.attributeTypeMap;
    };
    BTRevisionCustomData.discriminator = undefined;
    BTRevisionCustomData.attributeTypeMap = [
        {
            "name": "validRevisionReference",
            "baseName": "validRevisionReference",
            "type": "boolean"
        },
        {
            "name": "revision",
            "baseName": "revision",
            "type": "string"
        },
        {
            "name": "partNumber",
            "baseName": "partNumber",
            "type": "string"
        },
        {
            "name": "typeId",
            "baseName": "typeId",
            "type": "number"
        },
        {
            "name": "connectionSource",
            "baseName": "connectionSource",
            "type": "BTConnection"
        },
        {
            "name": "exportTypeName",
            "baseName": "exportTypeName",
            "type": "string"
        },
        {
            "name": "unknownClass",
            "baseName": "unknownClass",
            "type": "boolean"
        }
    ];
    return BTRevisionCustomData;
}());
exports.BTRevisionCustomData = BTRevisionCustomData;
