"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTReleasePackageParams = /** @class */ (function () {
    function BTReleasePackageParams() {
    }
    BTReleasePackageParams.getAttributeTypeMap = function () {
        return BTReleasePackageParams.attributeTypeMap;
    };
    BTReleasePackageParams.discriminator = undefined;
    BTReleasePackageParams.attributeTypeMap = [
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BTReleasePackageItemParams>"
        }
    ];
    return BTReleasePackageParams;
}());
exports.BTReleasePackageParams = BTReleasePackageParams;
