"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTRepairContextParams = /** @class */ (function () {
    function BTRepairContextParams() {
    }
    BTRepairContextParams.getAttributeTypeMap = function () {
        return BTRepairContextParams.attributeTypeMap;
    };
    BTRepairContextParams.discriminator = undefined;
    BTRepairContextParams.attributeTypeMap = [
        {
            "name": "oldOccurrences",
            "baseName": "oldOccurrences",
            "type": "Array<BTOccurrence>"
        },
        {
            "name": "newOccurrences",
            "baseName": "newOccurrences",
            "type": "Array<BTOccurrence>"
        },
        {
            "name": "contextAssemblyId",
            "baseName": "contextAssemblyId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "contextId",
            "baseName": "contextId",
            "type": "string"
        }
    ];
    return BTRepairContextParams;
}());
exports.BTRepairContextParams = BTRepairContextParams;
