"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTStandardContentHierarchyInfo = /** @class */ (function () {
    function BTStandardContentHierarchyInfo() {
    }
    BTStandardContentHierarchyInfo.getAttributeTypeMap = function () {
        return BTStandardContentHierarchyInfo.attributeTypeMap;
    };
    BTStandardContentHierarchyInfo.discriminator = undefined;
    BTStandardContentHierarchyInfo.attributeTypeMap = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        },
        {
            "name": "existingVersions",
            "baseName": "existingVersions",
            "type": "Array<VersionSpecs>"
        },
        {
            "name": "documentType",
            "baseName": "documentType",
            "type": "number"
        },
        {
            "name": "defaultWorkspace",
            "baseName": "defaultWorkspace",
            "type": "string"
        },
        {
            "name": "standard",
            "baseName": "standard",
            "type": "string"
        },
        {
            "name": "types",
            "baseName": "types",
            "type": "string"
        },
        {
            "name": "category",
            "baseName": "category",
            "type": "string"
        },
        {
            "name": "productionVersionId",
            "baseName": "productionVersionId",
            "type": "string"
        },
        {
            "name": "testVersionId",
            "baseName": "testVersionId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }
    ];
    return BTStandardContentHierarchyInfo;
}());
exports.BTStandardContentHierarchyInfo = BTStandardContentHierarchyInfo;
