/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BTComponentUsagesSummary } from './bTComponentUsagesSummary';
import { BTUserUsagesSummary } from './bTUserUsagesSummary';

export class BTStandardContentUsageSummary {
    'workspaceUseCount'?: number;
    'topUsedComponentsByWorkspaces'?: { [key: string]: BTComponentUsagesSummary; };
    'latestVersionUseCount'?: number;
    'topUsedComponentsByLatestVersions'?: { [key: string]: BTComponentUsagesSummary; };
    'versionUseCount'?: number;
    'topComponentsUsedAlongWithByLatestVersions'?: { [key: string]: BTComponentUsagesSummary; };
    'topUsersByWorkspaces'?: { [key: string]: BTUserUsagesSummary; };
    'topUsersByLatestVersions'?: { [key: string]: BTUserUsagesSummary; };
    'topUsersSummaryDone'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workspaceUseCount",
            "baseName": "workspaceUseCount",
            "type": "number"
        },
        {
            "name": "topUsedComponentsByWorkspaces",
            "baseName": "topUsedComponentsByWorkspaces",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "latestVersionUseCount",
            "baseName": "latestVersionUseCount",
            "type": "number"
        },
        {
            "name": "topUsedComponentsByLatestVersions",
            "baseName": "topUsedComponentsByLatestVersions",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "versionUseCount",
            "baseName": "versionUseCount",
            "type": "number"
        },
        {
            "name": "topComponentsUsedAlongWithByLatestVersions",
            "baseName": "topComponentsUsedAlongWithByLatestVersions",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "topUsersByWorkspaces",
            "baseName": "topUsersByWorkspaces",
            "type": "{ [key: string]: BTUserUsagesSummary; }"
        },
        {
            "name": "topUsersByLatestVersions",
            "baseName": "topUsersByLatestVersions",
            "type": "{ [key: string]: BTUserUsagesSummary; }"
        },
        {
            "name": "topUsersSummaryDone",
            "baseName": "topUsersSummaryDone",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BTStandardContentUsageSummary.attributeTypeMap;
    }
}

