"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTStandardContentUsageSummary = /** @class */ (function () {
    function BTStandardContentUsageSummary() {
    }
    BTStandardContentUsageSummary.getAttributeTypeMap = function () {
        return BTStandardContentUsageSummary.attributeTypeMap;
    };
    BTStandardContentUsageSummary.discriminator = undefined;
    BTStandardContentUsageSummary.attributeTypeMap = [
        {
            "name": "workspaceUseCount",
            "baseName": "workspaceUseCount",
            "type": "number"
        },
        {
            "name": "topUsedComponentsByWorkspaces",
            "baseName": "topUsedComponentsByWorkspaces",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "latestVersionUseCount",
            "baseName": "latestVersionUseCount",
            "type": "number"
        },
        {
            "name": "topUsedComponentsByLatestVersions",
            "baseName": "topUsedComponentsByLatestVersions",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "versionUseCount",
            "baseName": "versionUseCount",
            "type": "number"
        },
        {
            "name": "topComponentsUsedAlongWithByLatestVersions",
            "baseName": "topComponentsUsedAlongWithByLatestVersions",
            "type": "{ [key: string]: BTComponentUsagesSummary; }"
        },
        {
            "name": "topUsersByWorkspaces",
            "baseName": "topUsersByWorkspaces",
            "type": "{ [key: string]: BTUserUsagesSummary; }"
        },
        {
            "name": "topUsersByLatestVersions",
            "baseName": "topUsersByLatestVersions",
            "type": "{ [key: string]: BTUserUsagesSummary; }"
        },
        {
            "name": "topUsersSummaryDone",
            "baseName": "topUsersSummaryDone",
            "type": "boolean"
        }
    ];
    return BTStandardContentUsageSummary;
}());
exports.BTStandardContentUsageSummary = BTStandardContentUsageSummary;
