/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTUpdateElementThumbnailParams {
    'workspaceId'?: string;
    'elementId'?: string;
    'versionId'?: string;
    'encodedConfigurationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "workspaceId",
            "baseName": "workspaceId",
            "type": "string"
        },
        {
            "name": "elementId",
            "baseName": "elementId",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "encodedConfigurationId",
            "baseName": "encodedConfigurationId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTUpdateElementThumbnailParams.attributeTypeMap;
    }
}

