"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTUploadStateParams = /** @class */ (function () {
    function BTUploadStateParams() {
    }
    BTUploadStateParams.getAttributeTypeMap = function () {
        return BTUploadStateParams.attributeTypeMap;
    };
    BTUploadStateParams.discriminator = undefined;
    BTUploadStateParams.attributeTypeMap = [
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        }
    ];
    return BTUploadStateParams;
}());
exports.BTUploadStateParams = BTUploadStateParams;
