"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTUpdateReleasePackageParams = /** @class */ (function () {
    function BTUpdateReleasePackageParams() {
    }
    BTUpdateReleasePackageParams.getAttributeTypeMap = function () {
        return BTUpdateReleasePackageParams.attributeTypeMap;
    };
    BTUpdateReleasePackageParams.discriminator = undefined;
    BTUpdateReleasePackageParams.attributeTypeMap = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<BTPropertyValueParam>"
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<BTReleasePackageItemParams>"
        },
        {
            "name": "itemIds",
            "baseName": "itemIds",
            "type": "Array<string>"
        }
    ];
    return BTUpdateReleasePackageParams;
}());
exports.BTUpdateReleasePackageParams = BTUpdateReleasePackageParams;
