"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTUserActivationParams = /** @class */ (function () {
    function BTUserActivationParams() {
    }
    BTUserActivationParams.getAttributeTypeMap = function () {
        return BTUserActivationParams.attributeTypeMap;
    };
    BTUserActivationParams.discriminator = undefined;
    BTUserActivationParams.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "defaultCompanyName",
            "baseName": "defaultCompanyName",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "number"
        }
    ];
    return BTUserActivationParams;
}());
exports.BTUserActivationParams = BTUserActivationParams;
