"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTVersionOrWorkspaceInfo = /** @class */ (function () {
    function BTVersionOrWorkspaceInfo() {
    }
    BTVersionOrWorkspaceInfo.getAttributeTypeMap = function () {
        return BTVersionOrWorkspaceInfo.attributeTypeMap;
    };
    BTVersionOrWorkspaceInfo.discriminator = undefined;
    BTVersionOrWorkspaceInfo.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string"
        }
    ];
    return BTVersionOrWorkspaceInfo;
}());
exports.BTVersionOrWorkspaceInfo = BTVersionOrWorkspaceInfo;
