"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTWebhookOptions = /** @class */ (function () {
    function BTWebhookOptions() {
    }
    BTWebhookOptions.getAttributeTypeMap = function () {
        return BTWebhookOptions.attributeTypeMap;
    };
    BTWebhookOptions.discriminator = undefined;
    BTWebhookOptions.attributeTypeMap = [
        {
            "name": "collapseEvents",
            "baseName": "collapseEvents",
            "type": "boolean"
        }
    ];
    return BTWebhookOptions;
}());
exports.BTWebhookOptions = BTWebhookOptions;
