"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var BTWorkflowActionInfo = /** @class */ (function () {
    function BTWorkflowActionInfo() {
    }
    BTWorkflowActionInfo.getAttributeTypeMap = function () {
        return BTWorkflowActionInfo.attributeTypeMap;
    };
    BTWorkflowActionInfo.discriminator = undefined;
    BTWorkflowActionInfo.attributeTypeMap = [
        {
            "name": "tooltip",
            "baseName": "tooltip",
            "type": "string"
        },
        {
            "name": "allowIfNoApprovers",
            "baseName": "allowIfNoApprovers",
            "type": "boolean"
        },
        {
            "name": "allowIfApprovers",
            "baseName": "allowIfApprovers",
            "type": "boolean"
        },
        {
            "name": "alwaysAllow",
            "baseName": "alwaysAllow",
            "type": "boolean"
        },
        {
            "name": "isApproverAction",
            "baseName": "isApproverAction",
            "type": "boolean"
        },
        {
            "name": "label",
            "baseName": "label",
            "type": "string"
        },
        {
            "name": "isAdminOverride",
            "baseName": "isAdminOverride",
            "type": "boolean"
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string"
        },
        {
            "name": "requiredProperties",
            "baseName": "requiredProperties",
            "type": "Array<string>"
        },
        {
            "name": "uiHint",
            "baseName": "uiHint",
            "type": "string"
        }
    ];
    return BTWorkflowActionInfo;
}());
exports.BTWorkflowActionInfo = BTWorkflowActionInfo;
