"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var CloudObjectPathSegment = /** @class */ (function () {
    function CloudObjectPathSegment() {
    }
    CloudObjectPathSegment.getAttributeTypeMap = function () {
        return CloudObjectPathSegment.attributeTypeMap;
    };
    CloudObjectPathSegment.discriminator = undefined;
    CloudObjectPathSegment.attributeTypeMap = [
        {
            "name": "cloudStorageProviderType",
            "baseName": "cloudStorageProviderType",
            "type": "number"
        },
        {
            "name": "cloudStorageAccountId",
            "baseName": "cloudStorageAccountId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "treeHref",
            "baseName": "treeHref",
            "type": "string"
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "string"
        },
        {
            "name": "subType",
            "baseName": "subType",
            "type": "number"
        }
    ];
    return CloudObjectPathSegment;
}());
exports.CloudObjectPathSegment = CloudObjectPathSegment;
