"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.93
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var FormDataMultiPart = /** @class */ (function () {
    function FormDataMultiPart() {
    }
    FormDataMultiPart.getAttributeTypeMap = function () {
        return FormDataMultiPart.attributeTypeMap;
    };
    FormDataMultiPart.discriminator = undefined;
    FormDataMultiPart.attributeTypeMap = [
        {
            "name": "contentDisposition",
            "baseName": "contentDisposition",
            "type": "ContentDisposition"
        },
        {
            "name": "entity",
            "baseName": "entity",
            "type": "any"
        },
        {
            "name": "headers",
            "baseName": "headers",
            "type": "BodyPartHeaders"
        },
        {
            "name": "mediaType",
            "baseName": "mediaType",
            "type": "BodyPartMediaType"
        },
        {
            "name": "messageBodyWorkers",
            "baseName": "messageBodyWorkers",
            "type": "MessageBodyWorkers"
        },
        {
            "name": "parent",
            "baseName": "parent",
            "type": "MultiPart"
        },
        {
            "name": "providers",
            "baseName": "providers",
            "type": "any"
        },
        {
            "name": "bodyParts",
            "baseName": "bodyParts",
            "type": "Array<BodyPart>"
        },
        {
            "name": "fields",
            "baseName": "fields",
            "type": "{ [key: string]: Array<FormDataBodyPart>; }"
        },
        {
            "name": "parameterizedHeaders",
            "baseName": "parameterizedHeaders",
            "type": "BodyPartHeaders"
        }
    ];
    return FormDataMultiPart;
}());
exports.FormDataMultiPart = FormDataMultiPart;
