/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class GlobalPermissionInfo {
    'accessReports'?: boolean;
    'createProject'?: boolean;
    'approveReleases'?: boolean;
    'manageRbac'?: boolean;
    'manageUsers'?: boolean;
    'manageGuestUsers'?: boolean;
    'createReleases'?: boolean;
    'shareForAnonymousAccess'?: boolean;
    'deletePermanently'?: boolean;
    'adminEnterprise'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "accessReports",
            "baseName": "accessReports",
            "type": "boolean"
        },
        {
            "name": "createProject",
            "baseName": "createProject",
            "type": "boolean"
        },
        {
            "name": "approveReleases",
            "baseName": "approveReleases",
            "type": "boolean"
        },
        {
            "name": "manageRbac",
            "baseName": "manageRbac",
            "type": "boolean"
        },
        {
            "name": "manageUsers",
            "baseName": "manageUsers",
            "type": "boolean"
        },
        {
            "name": "manageGuestUsers",
            "baseName": "manageGuestUsers",
            "type": "boolean"
        },
        {
            "name": "createReleases",
            "baseName": "createReleases",
            "type": "boolean"
        },
        {
            "name": "shareForAnonymousAccess",
            "baseName": "shareForAnonymousAccess",
            "type": "boolean"
        },
        {
            "name": "deletePermanently",
            "baseName": "deletePermanently",
            "type": "boolean"
        },
        {
            "name": "adminEnterprise",
            "baseName": "adminEnterprise",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return GlobalPermissionInfo.attributeTypeMap;
    }
}

