"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var Message = /** @class */ (function () {
    function Message() {
    }
    Message.getAttributeTypeMap = function () {
        return Message.attributeTypeMap;
    };
    Message.discriminator = undefined;
    Message.attributeTypeMap = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "defaultTitle",
            "baseName": "defaultTitle",
            "type": "string"
        },
        {
            "name": "defaultTemplate",
            "baseName": "defaultTemplate",
            "type": "string"
        },
        {
            "name": "messageLevel",
            "baseName": "messageLevel",
            "type": "Message.MessageLevelEnum"
        }
    ];
    return Message;
}());
exports.Message = Message;
(function (Message) {
    var MessageLevelEnum;
    (function (MessageLevelEnum) {
        MessageLevelEnum[MessageLevelEnum["INFO"] = 'INFO'] = "INFO";
        MessageLevelEnum[MessageLevelEnum["WARNING"] = 'WARNING'] = "WARNING";
        MessageLevelEnum[MessageLevelEnum["ERROR"] = 'ERROR'] = "ERROR";
        MessageLevelEnum[MessageLevelEnum["MARKETING"] = 'MARKETING'] = "MARKETING";
        MessageLevelEnum[MessageLevelEnum["PRODUCT"] = 'PRODUCT'] = "PRODUCT";
        MessageLevelEnum[MessageLevelEnum["IMPORTANT"] = 'IMPORTANT'] = "IMPORTANT";
        MessageLevelEnum[MessageLevelEnum["ACTION"] = 'ACTION'] = "ACTION";
    })(MessageLevelEnum = Message.MessageLevelEnum || (Message.MessageLevelEnum = {}));
})(Message = exports.Message || (exports.Message = {}));
exports.Message = Message;
