"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var OAuthFlow = /** @class */ (function () {
    function OAuthFlow() {
    }
    OAuthFlow.getAttributeTypeMap = function () {
        return OAuthFlow.attributeTypeMap;
    };
    OAuthFlow.discriminator = undefined;
    OAuthFlow.attributeTypeMap = [
        {
            "name": "authorizationUrl",
            "baseName": "authorizationUrl",
            "type": "string"
        },
        {
            "name": "tokenUrl",
            "baseName": "tokenUrl",
            "type": "string"
        },
        {
            "name": "refreshUrl",
            "baseName": "refreshUrl",
            "type": "string"
        },
        {
            "name": "scopes",
            "baseName": "scopes",
            "type": "OAuthFlowScopes"
        },
        {
            "name": "extensions",
            "baseName": "extensions",
            "type": "{ [key: string]: any; }"
        }
    ];
    return OAuthFlow;
}());
exports.OAuthFlow = OAuthFlow;
