"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var UpdateParams = /** @class */ (function () {
    function UpdateParams() {
    }
    UpdateParams.getAttributeTypeMap = function () {
        return UpdateParams.attributeTypeMap;
    };
    UpdateParams.discriminator = undefined;
    UpdateParams.attributeTypeMap = [
        {
            "name": "idsToUpdate",
            "baseName": "idsToUpdate",
            "type": "Array<string>"
        },
        {
            "name": "fromReference",
            "baseName": "fromReference",
            "type": "BTUniqueDocumentItemParams"
        },
        {
            "name": "toReference",
            "baseName": "toReference",
            "type": "BTUniqueDocumentItemParams"
        }
    ];
    return UpdateParams;
}());
exports.UpdateParams = UpdateParams;
