"use strict";
/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
var XML = /** @class */ (function () {
    function XML() {
    }
    XML.getAttributeTypeMap = function () {
        return XML.attributeTypeMap;
    };
    XML.discriminator = undefined;
    XML.attributeTypeMap = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "string"
        },
        {
            "name": "prefix",
            "baseName": "prefix",
            "type": "string"
        },
        {
            "name": "attribute",
            "baseName": "attribute",
            "type": "boolean"
        },
        {
            "name": "wrapped",
            "baseName": "wrapped",
            "type": "boolean"
        },
        {
            "name": "extensions",
            "baseName": "extensions",
            "type": "{ [key: string]: any; }"
        }
    ];
    return XML;
}());
exports.XML = XML;
