/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTAclParams {
    '_public'?: boolean;
    'anonymousAccessAllowed'?: boolean;
    'anonymousAllowsExport'?: boolean;
    'documentId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "_public",
            "baseName": "public",
            "type": "boolean"
        },
        {
            "name": "anonymousAccessAllowed",
            "baseName": "anonymousAccessAllowed",
            "type": "boolean"
        },
        {
            "name": "anonymousAllowsExport",
            "baseName": "anonymousAllowsExport",
            "type": "boolean"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTAclParams.attributeTypeMap;
    }
}

