/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTApplicationElementThumbnailParams {
    'description'?: string;
    'isPrimary'?: boolean;
    'uniqueId'?: string;
    'base64EncodedImage'?: string;
    'imageWidth'?: number;
    'imageHeight'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "isPrimary",
            "baseName": "isPrimary",
            "type": "boolean"
        },
        {
            "name": "uniqueId",
            "baseName": "uniqueId",
            "type": "string"
        },
        {
            "name": "base64EncodedImage",
            "baseName": "base64EncodedImage",
            "type": "string"
        },
        {
            "name": "imageWidth",
            "baseName": "imageWidth",
            "type": "number"
        },
        {
            "name": "imageHeight",
            "baseName": "imageHeight",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BTApplicationElementThumbnailParams.attributeTypeMap;
    }
}

