/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTBillingPlanParams {
    'name'?: string;
    'group'?: string;
    'description'?: string;
    'planType'?: number;
    'trialPeriodDays'?: number;
    'consumableQuantity'?: number;
    'amountCents'?: number;
    'hidden'?: boolean;
    'planId'?: string;
    'clientId'?: string;
    'interval'?: string;
    'applicationId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "planType",
            "baseName": "planType",
            "type": "number"
        },
        {
            "name": "trialPeriodDays",
            "baseName": "trialPeriodDays",
            "type": "number"
        },
        {
            "name": "consumableQuantity",
            "baseName": "consumableQuantity",
            "type": "number"
        },
        {
            "name": "amountCents",
            "baseName": "amountCents",
            "type": "number"
        },
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "boolean"
        },
        {
            "name": "planId",
            "baseName": "planId",
            "type": "string"
        },
        {
            "name": "clientId",
            "baseName": "clientId",
            "type": "string"
        },
        {
            "name": "interval",
            "baseName": "interval",
            "type": "string"
        },
        {
            "name": "applicationId",
            "baseName": "applicationId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTBillingPlanParams.attributeTypeMap;
    }
}

