/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BTOwnerInfo } from './bTOwnerInfo';
import { BTThumbnailInfo } from './bTThumbnailInfo';
import { BTUserBasicSummaryInfo } from './bTUserBasicSummaryInfo';

export class BTCloudStorageObjectInfo {
    'mimeType'?: string;
    'thumbnailInfo'?: BTThumbnailInfo;
    'cloudStorageObjectId'?: string;
    'sizeBytes'?: number;
    'parentId'?: string;
    'cloudStorageProvider'?: number;
    'cloudStorageAccountId'?: string;
    'webViewLink'?: string;
    'iconLink'?: string;
    'createdById'?: string;
    'modifiedById'?: string;
    'owner'?: BTOwnerInfo;
    'description'?: string;
    'treeHref'?: string;
    'isMutable'?: boolean;
    'resourceType'?: string;
    'createdAt'?: Date;
    'createdBy'?: BTUserBasicSummaryInfo;
    'modifiedBy'?: BTUserBasicSummaryInfo;
    'modifiedAt'?: Date;
    'projectId'?: string;
    'canMove'?: boolean;
    'isContainer'?: boolean;
    'isEnterpriseOwned'?: boolean;
    'hasPendingOwner'?: boolean;
    'name'?: string;
    'id'?: string;
    'href'?: string;
    'viewRef'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mimeType",
            "baseName": "mimeType",
            "type": "string"
        },
        {
            "name": "thumbnailInfo",
            "baseName": "thumbnailInfo",
            "type": "BTThumbnailInfo"
        },
        {
            "name": "cloudStorageObjectId",
            "baseName": "cloudStorageObjectId",
            "type": "string"
        },
        {
            "name": "sizeBytes",
            "baseName": "sizeBytes",
            "type": "number"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "string"
        },
        {
            "name": "cloudStorageProvider",
            "baseName": "cloudStorageProvider",
            "type": "number"
        },
        {
            "name": "cloudStorageAccountId",
            "baseName": "cloudStorageAccountId",
            "type": "string"
        },
        {
            "name": "webViewLink",
            "baseName": "webViewLink",
            "type": "string"
        },
        {
            "name": "iconLink",
            "baseName": "iconLink",
            "type": "string"
        },
        {
            "name": "createdById",
            "baseName": "createdById",
            "type": "string"
        },
        {
            "name": "modifiedById",
            "baseName": "modifiedById",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "BTOwnerInfo"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "treeHref",
            "baseName": "treeHref",
            "type": "string"
        },
        {
            "name": "isMutable",
            "baseName": "isMutable",
            "type": "boolean"
        },
        {
            "name": "resourceType",
            "baseName": "resourceType",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "BTUserBasicSummaryInfo"
        },
        {
            "name": "modifiedBy",
            "baseName": "modifiedBy",
            "type": "BTUserBasicSummaryInfo"
        },
        {
            "name": "modifiedAt",
            "baseName": "modifiedAt",
            "type": "Date"
        },
        {
            "name": "projectId",
            "baseName": "projectId",
            "type": "string"
        },
        {
            "name": "canMove",
            "baseName": "canMove",
            "type": "boolean"
        },
        {
            "name": "isContainer",
            "baseName": "isContainer",
            "type": "boolean"
        },
        {
            "name": "isEnterpriseOwned",
            "baseName": "isEnterpriseOwned",
            "type": "boolean"
        },
        {
            "name": "hasPendingOwner",
            "baseName": "hasPendingOwner",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string"
        },
        {
            "name": "viewRef",
            "baseName": "viewRef",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTCloudStorageObjectInfo.attributeTypeMap;
    }
}

