/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BTDocumentElementInfo } from './bTDocumentElementInfo';

export class BTDocumentMergeInfo {
    'overwrittenElements'?: Array<BTDocumentElementInfo>;
    'libraryVersionMismatch'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "overwrittenElements",
            "baseName": "overwrittenElements",
            "type": "Array<BTDocumentElementInfo>"
        },
        {
            "name": "libraryVersionMismatch",
            "baseName": "libraryVersionMismatch",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BTDocumentMergeInfo.attributeTypeMap;
    }
}

