/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTDocumentOptionsParams {
    'cppServerLimit'?: number;
    'thumbnailCppServerLimit'?: number;
    'linkedCppServerLimit'?: number;
    'drawingServerMemory'?: number;
    'cppServerDefaultElementLimit'?: number;
    'cppServerMemory'?: number;
    'enableCppServerMemoryDiagnostics'?: boolean;
    'extendedDisplayCheck'?: boolean;
    'skipRetrievalTest'?: boolean;
    'documentMemory'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cppServerLimit",
            "baseName": "cppServerLimit",
            "type": "number"
        },
        {
            "name": "thumbnailCppServerLimit",
            "baseName": "thumbnailCppServerLimit",
            "type": "number"
        },
        {
            "name": "linkedCppServerLimit",
            "baseName": "linkedCppServerLimit",
            "type": "number"
        },
        {
            "name": "drawingServerMemory",
            "baseName": "drawingServerMemory",
            "type": "number"
        },
        {
            "name": "cppServerDefaultElementLimit",
            "baseName": "cppServerDefaultElementLimit",
            "type": "number"
        },
        {
            "name": "cppServerMemory",
            "baseName": "cppServerMemory",
            "type": "number"
        },
        {
            "name": "enableCppServerMemoryDiagnostics",
            "baseName": "enableCppServerMemoryDiagnostics",
            "type": "boolean"
        },
        {
            "name": "extendedDisplayCheck",
            "baseName": "extendedDisplayCheck",
            "type": "boolean"
        },
        {
            "name": "skipRetrievalTest",
            "baseName": "skipRetrievalTest",
            "type": "boolean"
        },
        {
            "name": "documentMemory",
            "baseName": "documentMemory",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return BTDocumentOptionsParams.attributeTypeMap;
    }
}

