/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BTStandardContentParameterDefinition } from './bTStandardContentParameterDefinition';

export class BTStandardContentParams {
    'parameters'?: Array<BTStandardContentParameterDefinition>;
    'parametersId'?: string;
    'parametersIdVersion'?: string;
    'targetDocumentId'?: string;
    'targetElementId'?: string;
    'saveCustomProperties'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "parameters",
            "baseName": "parameters",
            "type": "Array<BTStandardContentParameterDefinition>"
        },
        {
            "name": "parametersId",
            "baseName": "parametersId",
            "type": "string"
        },
        {
            "name": "parametersIdVersion",
            "baseName": "parametersIdVersion",
            "type": "string"
        },
        {
            "name": "targetDocumentId",
            "baseName": "targetDocumentId",
            "type": "string"
        },
        {
            "name": "targetElementId",
            "baseName": "targetElementId",
            "type": "string"
        },
        {
            "name": "saveCustomProperties",
            "baseName": "saveCustomProperties",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return BTStandardContentParams.attributeTypeMap;
    }
}

