/**
 * Onshape REST API
 * The Onshape REST API consumed by all clients.
 *
 * OpenAPI spec version: 1.96
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export class BTUserNotificationPrefParams {
    'type'?: number;
    'objectType'?: number;
    'level'?: number;
    'objectId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "number"
        },
        {
            "name": "objectType",
            "baseName": "objectType",
            "type": "number"
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number"
        },
        {
            "name": "objectId",
            "baseName": "objectId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return BTUserNotificationPrefParams.attributeTypeMap;
    }
}

